version: '2'
services:
  web1:
    image: nginx
    ports:
      - "39999:80"
    volumes:
      - ./nginx/beego-nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx-web1

  go-base:
    build: ./beego/
    image: go-base:v0.1

  beego-web1:
    image: go-base:v0.1
    volumes:
      - ./beego-1/test1.go:/root/go/src/myTest/test.go
    ports:
      - "10086:8080"
    container_name: beego-web1
    depends_on:
      - go-base

  beego-web2:
    image: go-base:v0.1
    volumes:
      - ./beego-2/test2.go:/root/go/src/myTest/test.go
    ports:
      - "10087:8080"
    container_name: beego-web2
    depends_on:
      - go-base

